apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: spring-boot-deployment

spec:
  selector:
    app: product-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: "TCP"
  type: NodePort