
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    hikari:
#      initialization-fail-timeout: 0
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update

#spring:
#  # Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/productdb
#    username: root
#    password: "password"
#    # Hibernate Properties
#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true